# Generated by Django 5.0.6 on 2024-05-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='ProductSubCategory',
        ),
    ]
